### ISSUE TITLE
Weights file missing?

### ISSUE THREAD

**Issue by ghost** [IVPLatNU/DeepCovidXR#3]
Code: ```utils/model_util.py```, line 155 attempts to load file ```InceptionResNet_{size}...h5``` which is not present in the weights downloaded from google drive.

I modifed the code to load what I _think_ is the correct file: ```utils/model_util.py```, line 155 now loads file with name:  ```Inception_{size}...h5``` (i.e. I dropped the "ResNet" out of the file name in the code).

Is this the correct weights file?

**Comment by rmw362** [comment]
Hi Gaby, no there should be weight files for both Inception and InceptionResNet. I confirmed both are present (see attached screenshot)

![Screen Shot 2020-11-25 at 9 59 21 PM](https://user-images.githubusercontent.com/65331476/100306716-9f8fb900-2f69-11eb-8f40-f5cd86c64d8b.png)

**Comment by rmw362** [comment]
Let me know if you are having trouble accessing these weight files

**Comment by ghost** [comment]
Thanks for the quick clarification / confirmation, appreciated. Those files were definitely not present in the original "download all" zip files I got from google drive, but they are in the zip files I just re-downloaded this morning. Strange, but whatever... at least we're making progress, thanks :)
