### ISSUE TITLE
Error in loading the saved optimizer state

### ISSUE THREAD

**Issue by ghost** [IVPLatNU/DeepCovidXR#4]
Hi,
Got the weights files sorted out.
Next issue when running ```predict.py```:
```
[...]/python3.6/dist-packages/keras/engine/saving.py:384: UserWarning: Error in loading the saved optimizer state. As a result, your model is starting with a freshly initialized optimizer.
  warnings.warn('Error in loading the saved optimizer '
```
(Note: using Python3.**6** as most packages in the requirements.txt get downloaded with __cp36__ in the name, suggesting that Python 3.6 would be the best environment fit)

Is the warning/error about loading the saved optimizer state something I need to be concerned about?

**Comment by rmw362** [comment]
Hi Gaby, no this is not an issue. This comes from not specifying the argument compile=False in the call to Keras's load_model module when loading the UNet for lung segmentation. The optimizer saved state is not necessary as we are not training this model any further, just using the saved weights for inference. We have updated crop_img.py and this warning should no longer appear. 

Closing this issue given it is now resolved.
